INSERT INTO USUARIO(NOMBRE,EMAIL,CONTRASENA) VALUES("alumno", "alumno@gmail.com", "123456")

INSERT INTO CURSO(NOMBRE,CATEGORIA) VALUES("Spring" , "Desarrollo Web")
INSERT INTO CURSO(NOMBRE,CATEGORIA) VALUES("IOS" , "Desarrollo Movil")
INSERT INTO CURSO(NOMBRE,CATEGORIA) VALUES("LINUX" , "DevOps")

INSERT INTO TOPICO(TITULO,MENSAJE,FECHA_CREACION,STATUS,AUTOR_ID,CURSO_ID) VALUES("Error","No me compila el Projecto", 2022-09-02, SIN_RESPUESTA, "Carlostro", "carlostro@gmail.com", "123456789" , "Linux" , "DevOps")
INSERT INTO TOPICO(TITULO,MENSAJE,FECHA_CREACION,STATUS,AUTOR_ID,CURSO_ID) VALUES("Error2","Teg HTML", 2022-07-07, SIN_RESPUESTA, "Carlostro", "carlostro@gmail.com", "123456789" , "IOS" , "Desarrollo Movil")
INSERT INTO TOPICO(TITULO,MENSAJE,FECHA_CREACION,STATUS,AUTOR_ID,CURSO_ID) VALUES("Error3","No Compila", 2022-05-04, SIN_RESPUESTA, "Carlostro", "carlostro@gmail.com", "123456789" , "Spring" , "Desarrollo Web")